# config/_default/menus.en.toml

# [[main]]
#   name = "About"
#   pageRef = "about"
#   weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Topics"
  pageRef = "topics"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "RSS"
  url = "/index.xml"
  weight = 90